ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DarkphotonNuc_UFO_3'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_55 = ', GC_55
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_57 = ', GC_57
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_90 = ', GC_90
      WRITE(*,2) 'GC_96 = ', GC_96
      WRITE(*,2) 'GC_111 = ', GC_111
